TOP=../..

include $(TOP)/configure/CONFIG

PROD_IOC += dbToDoxygen

dbToDoxygen_SRCS += dbToDoxygen.cpp
dbToDoxygen_LIBS += $(EPICS_BASE_IOC_LIBS)

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

